// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tdnktspqirmrpcfvufca.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkbmt0c3BxaXJtcnBjZnZ1ZmNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NDU0NzIsImV4cCI6MjA2NTIyMTQ3Mn0.6gFips8osgqZnmVY5EKifDo6b82kYfi6THSs2jridNE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);